version: '3.8'

services:
  redis:
    image: redis:7.0.12-alpine
    container_name: redis
    ports:
      - "6379:6379"
  mysql:
    env_file: ./.env
    image: mysql:8.0.34
    container_name: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_ROOT_PASSWORD": "${DB_PASSWORD}"
